config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
    # /restaurants/:id
    resources :reviews, only: [:new, :create, :show]
    # /restaurants/:id/review/new
  end
  # resources :review, only: [:new, :create]
  # reviews/new
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, :address, presence: true
  validates :category, presence: true, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"]}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, :rating, presence: true
  validates :rating, numericality: { only_integer: true }, inclusion: { in: [0, 1, 2, 3, 4, 5] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(@restaurant)
    else
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def show
    @review = Review.find(params[:id])
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    # set the id of restaurant to the review
    # @review.restaurant_id = params[:restaurant_id]
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category %>
  </div>

  <div class="form-actions btn btn-outline-success">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<!-- <%#= link_to 'Show', @restaurant %> | -->
<%= link_to 'Cancel', restaurants_path %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>
<% @restaurants.each do |restaurant| %>
<ul>
  <li>
    <%=  link_to restaurant_path(restaurant) do %>
      <%= restaurant.name %>
    <% end %>
    -
    <%= link_to edit_restaurant_path(restaurant) do %>
      <i class="far fa-edit"></i>
    <% end %>
  </li>
</ul>
<% end %>

<%= link_to "Add new restaurant", new_restaurant_path, class: "btn btn-outline-success" %>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%#= link_to 'Show', @restaurant %> |
<%= link_to 'Cancel', restaurants_path %>

app/views/restaurants/show.html.erb
<h1>
  <strong><%= @restaurant.name %></strong>
</h1>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @restaurant.phone_number %>
</p>

<p>
  <strong>Food type:</strong>
  <%= @restaurant.category %>
</p>

<h2><strong>Reviews</strong></h2>

<p>
  <% @restaurant.reviews.each do |review| %>
    <% review.rating.times do |time| %>
      <i class="fas fa-star"></i>
    <% end %>

    <% (5 - review.rating).times do |time| %>
      <i class="far fa-star"></i>
    <% end %> -


    <%= link_to restaurant_review_path(review) do %>
      <%= review.content %>
    <% end %>
  <% end %>
</p>


<%= link_to "Add review", new_restaurant_review_path(@restaurant) %>

<%= link_to edit_restaurant_path(@restaurant) do %>
    <p>Edit <i class="far fa-edit"></i></p>
<% end %>
<%= link_to 'Back', restaurants_path, class: "btn btn-outline-primary" %>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
<%= f.input :content %>
<%= f.input :rating %>
<%= f.submit %>
<% end %>

app/views/reviews/show.html.erb
<h1>
  <strong><%= @review.restaurant.name %></strong>
</h1>

<p>
  <%= @review.content %>
</p>


<p>
  <strong>Rating:</strong>
  <% @review.rating.times do |time| %>
    <i class="fas fa-star"></i>
  <% end %>

  <% (5 - @review.rating).times do |time| %>
    <i class="far fa-star"></i>
  <% end %>
</p>

<%=  link_to "Back", restaurant_path(@review.restaurant) %>